### ISSUE TITLE
staying in recovery mode after flashing system.img

### ISSUE THREAD

**Issue by msliu** [mozilla-b2g/android-device-galaxys2#4]
Tips to reproduce the issue
1. make sync
2. export ANDROIDFS_DIR=sgs2-android
3. make config-galaxy-s2-ics
4. make kernel
5. adb reboot download
6. heimdall flash --kernel boot/kernel-android-galaxy-s2-ics/arch/arm/boot/zImage
7. make gonk
8. make
9. make flash-only (flashing system.img)

Result: After 9, the device reboot and force to enter recovery mode.

**Comment by dhylands** [comment]
How big is the system.img file? Heimdall has problems flashing .img files larger than 100 Mb.

If your system.img is too big, then edit gonk-misc/Android.mk and around line 84 you should see:
cd $(TARGET_OUT) && tar xvfz $(abspath $<)

Comment out that line and rebuild. This should shrink the size of system.img. You'll need to do "make flash-gecko-only" or "./flash.sh gecko" depending on which build system you're using. Reboot the phone after installing gecko.

oh yeah - once you've commented out the tarball expansion, the phone will appear hung at the triangle screen. That's because b2g isn't running. adb should still be running (try adb shell) which is all that's needed for flashing gecko.

**Comment by msliu** [comment]
The size of my system.img is about 116.8MB. I try to comment out the line you suggest and run again 7 and 8. After that, run 9 to flash system.img. After all, the phone still reboot and force to enter recovery mode.

**Comment by shianyow** [comment]
After discussing with @michaelwu , it should be same issue as https://github.com/andreasgal/B2G/issues/302.
This issue only happens on old build system, or new build system for arm emulator.
Because google recently broke arm bionic on master, reverting glue/gonk-ics/bionic to below commit id should fix this issue.

<pre>
commit 4f05d1c758ba141c617f25251a661ecb66627e9e
Merge: edb7cad c47703a
Author: Elliott Hughes <enh@google.com>
Date:   Thu May 10 10:14:43 2012 -0700

    Merge "bionic/x86: Optimization for memcpy"
</pre>

**Comment by shianyow** [comment]
Fixed by https://github.com/mozilla-b2g/gonk-ics-manifest/commit/e330e3048d85469337f20eee3b27011336464a5c
